/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Material Design fragments, at
* https://www.jitblox.com/project/rVvXeSDSXs/material-design-fragments
*/

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatMenuModule } from '@angular/material/menu';
import { MatToolbarModule } from '@angular/material/toolbar';
import { RouterLink } from '@angular/router';

/**
* A double Material Design toolbar with two titles and a vertical Dropdown Menu and icons on the
* right.
* In order to turn the menu into a working navigation menu, configure each menu button's Router Link
* Destination and make sure that your app has a Router Outlet.
*/
@Component({
  selector: 'app-toolbar-with-2-rows-and-dropdown',
  standalone: true,
  templateUrl: './toolbar-with-2-rows-and-dropdown.component.html',
  styleUrls: ['./toolbar-with-2-rows-and-dropdown.component.scss'],
  imports: [MatToolbarModule, MatMenuModule, RouterLink, MatButtonModule, MatIconModule, CommonModule]
})
export class ToolbarWith2RowsAndDropdownComponent {

  constructor() {}
}
