/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Material Design fragments, at
* https://www.jitblox.com/project/rVvXeSDSXs/material-design-fragments
*/

import { CommonModule } from '@angular/common';
import { Component, ViewChild } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatListModule } from '@angular/material/list';
import { MatSidenavModule } from '@angular/material/sidenav';
import { MatToolbarModule } from '@angular/material/toolbar';
import { RouterLink, RouterOutlet } from '@angular/router';

/**
* A Material Design Sidenav containing a Navigation List. By default, the Sidenav can be toggled using
* the menu button in the toolbar but can be toggled by any other element by attaching a "click" event
* that calls leftSidenav.toggle().
* In order to turn the Sidenav into a working navigation menu, configure each list item's Router Link
* Destination with a component in your app.
*/
@Component({
  selector: 'app-basic-sidenav',
  standalone: true,
  templateUrl: './basic-sidenav.component.html',
  styleUrls: ['./basic-sidenav.component.scss'],
  imports: [MatToolbarModule, MatButtonModule, MatIconModule, MatSidenavModule, MatListModule, RouterLink, RouterOutlet, CommonModule]
})
export class BasicSidenavComponent {
  @ViewChild('leftSidenav') public leftSidenav: any;

  constructor() {}

  public onButton1Click($event: MouseEvent): void {
    this.leftSidenav.toggle();
  }
}
