/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Material Design fragments, at
* https://www.jitblox.com/project/rVvXeSDSXs/material-design-fragments
*/

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';

/**
* A grid of Material Design Cards. The grid is a pure CSS grid that is made responsive using a CSS
* 'minmax' rule.
*/
@Component({
  selector: 'app-responsive-cards',
  standalone: true,
  templateUrl: './responsive-cards.component.html',
  styleUrls: ['./responsive-cards.component.scss'],
  imports: [MatCardModule, MatButtonModule, CommonModule]
})
export class ResponsiveCardsComponent {

  constructor() {}
}
