/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Material Design fragments, at
* https://www.jitblox.com/project/rVvXeSDSXs/material-design-fragments
*/

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatToolbarModule } from '@angular/material/toolbar';
import { RouterLink, RouterOutlet } from '@angular/router';

/**
* This application contains ready-to-use Angular Material Design fragments that accelerate prototyping
* of modern web applications with JitBlox. All fragments in this project can be added to your Material
* Design project directly from the JitBlox toolbox.
*/
@Component({
  selector: 'app-root',
  standalone: true,
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  imports: [MatToolbarModule, MatButtonModule, RouterLink, MatIconModule, RouterOutlet, CommonModule]
})
export class AppComponent {

  constructor() {}
}
