/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Material Design fragments, at
* https://www.jitblox.com/project/rVvXeSDSXs/material-design-fragments
*/

import { Routes } from '@angular/router';
import { AppComponent } from './app.component';
import { _FeaturesComponent } from './components/Features/_-features.component';
import { ResponsiveCardsComponent } from './components/Features/responsive-cards.component';
import { _FormsComponent } from './components/Forms/_-forms.component';
import { MultiStepFormComponent } from './components/Forms/multi-step-form.component';
import { SimpleFormComponent } from './components/Forms/simple-form.component';
import { _HeadersComponent } from './components/Headers/_-headers.component';
import { BasicToolbarWithDropdownComponent } from './components/Headers/basic-toolbar-with-dropdown.component';
import { ToolbarWith2RowsAndDropdownComponent } from './components/Headers/toolbar-with-2-rows-and-dropdown.component';
import { _NavigationComponent } from './components/Navigation/_-navigation.component';
import { AccordionComponent } from './components/Navigation/accordion.component';
import { TabsWithRoutingComponent } from './components/Navigation/tabs-with-routing.component';
import { _SideNavsComponent } from './components/Sidenavs/_-side-navs.component';
import { BasicSidenavComponent } from './components/Sidenavs/basic-sidenav.component';
import { LeftAndRightSidenavComponent } from './components/Sidenavs/left-and-right-sidenav.component';

export const routes: Routes = [
  {
    path: 'app',
    component: AppComponent
  },
  {
    path: 'headers',
    component: _HeadersComponent,
    children: [
      {
        path: 'basic-toolbar-with-dropdown',
        component: BasicToolbarWithDropdownComponent
      },
      {
        path: 'toolbar-with-2-rows-and-dropdown',
        component: ToolbarWith2RowsAndDropdownComponent
      },
      {
        path: '',
        redirectTo: 'basic-toolbar-with-dropdown',
        pathMatch: 'full'
      }
    ]
  },
  {
    path: 'side-navs',
    component: _SideNavsComponent,
    children: [
      {
        path: 'basic-sidenav',
        component: BasicSidenavComponent
      },
      {
        path: 'left-and-right-sidenav',
        component: LeftAndRightSidenavComponent
      },
      {
        path: '',
        redirectTo: 'basic-sidenav',
        pathMatch: 'full'
      }
    ]
  },
  {
    path: 'forms',
    component: _FormsComponent,
    children: [
      {
        path: 'simple-form',
        component: SimpleFormComponent
      },
      {
        path: 'multi-step-form',
        component: MultiStepFormComponent
      },
      {
        path: '',
        redirectTo: 'simple-form',
        pathMatch: 'full'
      }
    ]
  },
  {
    path: 'navigation',
    component: _NavigationComponent,
    children: [
      {
        path: 'accordion',
        component: AccordionComponent
      },
      {
        path: 'tabs-with-routing',
        component: TabsWithRoutingComponent
      },
      {
        path: '',
        redirectTo: 'accordion',
        pathMatch: 'full'
      }
    ]
  },
  {
    path: 'features',
    component: _FeaturesComponent,
    children: [
      {
        path: 'responsive-cards',
        component: ResponsiveCardsComponent
      },
      {
        path: '',
        redirectTo: 'responsive-cards',
        pathMatch: 'full'
      }
    ]
  },
  {
    path: '',
    redirectTo: '/headers',
    pathMatch: 'full'
  }
];
