/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Material Design fragments, at
* https://www.jitblox.com/project/rVvXeSDSXs/material-design-fragments
*/

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';

/**
* A basic form containing Material Design Text input, dropdown, text area and phone input. Bind each
* input's value to a component property by setting the input's Model attribute.
*/
@Component({
  selector: 'app-simple-form',
  standalone: true,
  templateUrl: './simple-form.component.html',
  styleUrls: ['./simple-form.component.scss'],
  imports: [MatFormFieldModule, MatInputModule, FormsModule, MatSelectModule, MatIconModule, CommonModule]
})
export class SimpleFormComponent {

  constructor() {}
}
