/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Material Design fragments, at
* https://www.jitblox.com/project/rVvXeSDSXs/material-design-fragments
*/

import { CommonModule } from '@angular/common';
import { Component, ViewChild } from '@angular/core';
import { MatTabsModule } from '@angular/material/tabs';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';

/**
* This component supports navigating the fragments in this project and is hidden from the JitBlox
* toolbox.
*/
@Component({
  selector: 'app-_-navigation',
  standalone: true,
  templateUrl: './_-navigation.component.html',
  styleUrls: ['./_-navigation.component.scss'],
  imports: [MatTabsModule, RouterLink, RouterLinkActive, RouterOutlet, CommonModule]
})
export class _NavigationComponent {
  @ViewChild('navPanel') public navPanel: any;

  constructor() {}
}
