/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Material Design fragments, at
* https://www.jitblox.com/project/rVvXeSDSXs/material-design-fragments
*/

import { CommonModule } from '@angular/common';
import { Component, ViewChild } from '@angular/core';
import { MatTabsModule } from '@angular/material/tabs';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';

/**
* A Material Design Tab navbar with router links and a Router outlet. 
* In order to turn the navbar into a working navigation bar, configure each tab link's Router Link
* Destination with a component in your app.
*/
@Component({
  selector: 'app-tabs-with-routing',
  standalone: true,
  templateUrl: './tabs-with-routing.component.html',
  imports: [MatTabsModule, RouterLink, RouterLinkActive, RouterOutlet, CommonModule]
})
export class TabsWithRoutingComponent {
  @ViewChild('navPanel') public navPanel: any;

  constructor() {}
}
